name: pyDiffTools Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          wget -O Miniforge3.sh "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
          bash Miniforge3.sh -b -p "${HOME}/conda"
          source "${HOME}/conda/etc/profile.d/conda.sh"
          # For mamba support also run the following command
          source "${HOME}/conda/etc/profile.d/mamba.sh"
          conda activate base
          python -m pip install --upgrade pip
          pip install pytest
          conda install -y -c conda-forge pandoc-crossref
      - name: Install project for testing
        run: |
          source "${HOME}/conda/etc/profile.d/conda.sh"
          conda activate base
          pip install -e . --no-build-isolation
      - name: Run pytest
        run: |
          source "${HOME}/conda/etc/profile.d/conda.sh"
          conda activate base
          pytest
